<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns0="http://xmlns.oracle.com/VentasMovil/PM_ServicesProducts/PM_ServicesProducts"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns0 oraxsl xp20 xref mhdr oraext dvm socket"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:tns="http://xmlns.oracle.com/VentasMovil/PM_ServicesProducts/RestService">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/PM_ServicesProducts.wsdl"/>
        <oracle-xsl-mapper:rootElement name="processResponse"
                                       namespace="http://xmlns.oracle.com/VentasMovil/PM_ServicesProducts/PM_ServicesProducts"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/RestService.wsdl"/>
        <oracle-xsl-mapper:rootElement name="processResponse"
                                       namespace="http://xmlns.oracle.com/VentasMovil/PM_ServicesProducts/PM_ServicesProducts"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [THU OCT 19 21:05:30 CDT 2017].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <ns0:processResponse>
      <ns0:Result>
        <ns0:Result>
          <xsl:value-of select="/ns0:processResponse/ns0:Result/ns0:Result"/>
        </ns0:Result>
        <ns0:IdResult>
          <xsl:value-of select="/ns0:processResponse/ns0:Result/ns0:IdResult"/>
        </ns0:IdResult>
        <ns0:Description>
          <xsl:value-of select="/ns0:processResponse/ns0:Result/ns0:Description"/>
        </ns0:Description>
      </ns0:Result>
      <xsl:for-each select="/ns0:processResponse/ns0:ArrServiciosIncluidos">
        <ns0:ArrServiciosIncluidos>
          <ns0:Id>
            <xsl:value-of select="ns0:Id"/>
          </ns0:Id>
          <ns0:Nombre>
            <xsl:value-of select="ns0:Nombre"/>
          </ns0:Nombre>
          <ns0:CantidadEquiposAutomaticos>
            <xsl:value-of select="ns0:CantidadEquiposAutomaticos"/>
          </ns0:CantidadEquiposAutomaticos>
          <ns0:Comentario>
            <xsl:value-of select="ns0:Comentario"/>
          </ns0:Comentario>
          <ns0:MaximoAgregar>
            <xsl:value-of select="ns0:MaximoAgregar"/>
          </ns0:MaximoAgregar>
          <ns0:Nombrecomercial>
            <xsl:value-of select="ns0:Nombrecomercial"/>
          </ns0:Nombrecomercial>
          <ns0:NombreEditable>
            <xsl:value-of select="ns0:NombreEditable"/>
          </ns0:NombreEditable>
          <ns0:PlanId>
            <xsl:value-of select="ns0:PlanId"/>
          </ns0:PlanId>
          <ns0:Precio>
            <xsl:value-of select="ns0:Precio"/>
          </ns0:Precio>
          <ns0:SeActiva>
            <xsl:value-of select="ns0:SeActiva"/>
          </ns0:SeActiva>
          <ns0:SeFactura>
            <xsl:value-of select="ns0:SeFactura"/>
          </ns0:SeFactura>
          <ns0:ServicioId>
            <xsl:value-of select="ns0:ServicioId"/>
          </ns0:ServicioId>
          <ns0:SRV_Mode>
            <xsl:value-of select="ns0:SRV_Mode"/>
          </ns0:SRV_Mode>
          <ns0:TipoServicio>
            <xsl:value-of select="ns0:TipoServicio"/>
          </ns0:TipoServicio>
          <ns0:TipoTelefonia>
            <xsl:value-of select="ns0:TipoTelefonia"/>
          </ns0:TipoTelefonia>
          <ns0:Orden>
            <xsl:value-of select="ns0:Orden"/>
          </ns0:Orden>
          <xsl:for-each select="ns0:ArrProductosIncluidos">
            <ns0:ArrProductosIncluidos>
              <ns0:Id>
                <xsl:value-of select="ns0:Id"/>
              </ns0:Id>
              <ns0:Nombre>
                <xsl:value-of select="ns0:Nombre"/>
              </ns0:Nombre>
              <ns0:AgrupacionAddon>
                <xsl:value-of select="ns0:AgrupacionAddon"/>
              </ns0:AgrupacionAddon>
              <ns0:CantidadDN>
                <xsl:value-of select="ns0:CantidadDN"/>
              </ns0:CantidadDN>
              <ns0:CantidadTroncal>
                <xsl:value-of select="ns0:CantidadTroncal"/>
              </ns0:CantidadTroncal>
              <ns0:Comentario>
                <xsl:value-of select="ns0:Comentario"/>
              </ns0:Comentario>
              <ns0:EsAutomaticoCiudad>
                <xsl:value-of select="ns0:EsAutomaticoCiudad"/>
              </ns0:EsAutomaticoCiudad>
              <ns0:EsCargoUnico>
                <xsl:value-of select="ns0:EsCargoUnico"/>
              </ns0:EsCargoUnico>
              <ns0:Estatus>
                <xsl:value-of select="ns0:Estatus"/>
              </ns0:Estatus>
              <ns0:EsVisible>
                <xsl:value-of select="ns0:EsVisible"/>
              </ns0:EsVisible>
              <ns0:IdBrmArrear>
                <xsl:value-of select="ns0:IdBrmArrear"/>
              </ns0:IdBrmArrear>
              <ns0:IdBrmCU>
                <xsl:value-of select="ns0:IdBrmCU"/>
              </ns0:IdBrmCU>
              <ns0:IdBrmForward>
                <xsl:value-of select="ns0:IdBrmForward"/>
              </ns0:IdBrmForward>
              <ns0:IEPS>
                <xsl:value-of select="ns0:IEPS"/>
              </ns0:IEPS>
              <ns0:IVA>
                <xsl:value-of select="ns0:IVA"/>
              </ns0:IVA>
              <ns0:MaximoAgregar>
                <xsl:value-of select="ns0:MaximoAgregar"/>
              </ns0:MaximoAgregar>
              <ns0:NombreEditable>
                <xsl:value-of select="ns0:NombreEditable"/>
              </ns0:NombreEditable>
              <ns0:PlanDescuentoId>
                <xsl:value-of select="ns0:PlanDescuentoId"/>
              </ns0:PlanDescuentoId>
              <ns0:Plazo>
                <xsl:value-of select="ns0:Plazo"/>
              </ns0:Plazo>
              <ns0:PrecioBase>
                <xsl:value-of select="ns0:PrecioBase"/>
              </ns0:PrecioBase>
              <ns0:PrecioEditable>
                <xsl:value-of select="ns0:PrecioEditable"/>
              </ns0:PrecioEditable>
              <ns0:PrecioProntoPago>
                <xsl:value-of select="ns0:PrecioProntoPago"/>
              </ns0:PrecioProntoPago>
              <ns0:ProductoPadre>
                <xsl:value-of select="ns0:ProductoPadre"/>
              </ns0:ProductoPadre>
              <ns0:TipoProducto>
                <xsl:value-of select="ns0:TipoProducto"/>
              </ns0:TipoProducto>
              <ns0:IdProducto>
                <xsl:value-of select="ns0:IdProducto"/>
              </ns0:IdProducto>
              <ns0:NameProducto>
                <xsl:value-of select="ns0:NameProducto"/>
              </ns0:NameProducto>
              <ns0:ProductoId>
                <xsl:value-of select="ns0:ProductoId"/>
              </ns0:ProductoId>
              <ns0:Ciudad>
                <xsl:value-of select="ns0:Ciudad"/>
              </ns0:Ciudad>
              <ns0:VelocidadSubida>
                <xsl:value-of select="ns0:VelocidadSubida"/>
              </ns0:VelocidadSubida>
              <ns0:VelocidadBajada>
                <xsl:value-of select="ns0:VelocidadBajada"/>
              </ns0:VelocidadBajada>
              <ns0:TieneIPDinamica>
                <xsl:value-of select="ns0:TieneIPDinamica"/>
              </ns0:TieneIPDinamica>
              <ns0:TieneIPFija>
                <xsl:value-of select="ns0:TieneIPFija"/>
              </ns0:TieneIPFija>
              <ns0:TieneSTBAdicional>
                <xsl:value-of select="ns0:TieneSTBAdicional"/>
              </ns0:TieneSTBAdicional>
              <ns0:EsCCTV>
                <xsl:value-of select="ns0:EsCCTV"/>
              </ns0:EsCCTV>
              <ns0:EsWiFi>
                <xsl:value-of select="ns0:EsWiFi"/>
              </ns0:EsWiFi>
              <ns0:Cantidad>
                <xsl:value-of select="ns0:Cantidad"/>
              </ns0:Cantidad>
              <ns0:EstatusProducto>
                <xsl:value-of select="ns0:EstatusProducto"/>
              </ns0:EstatusProducto>
              <ns0:FechaInicio>
                <xsl:value-of select="ns0:FechaInicio"/>
              </ns0:FechaInicio>
              <ns0:FechaFin>
                <xsl:value-of select="ns0:FechaFin"/>
              </ns0:FechaFin>
              <ns0:ComentarioProducto>
                <xsl:value-of select="ns0:ComentarioProducto"/>
              </ns0:ComentarioProducto>
              <ns0:EsProntoPago>
                <xsl:value-of select="ns0:EsProntoPago"/>
              </ns0:EsProntoPago>
            </ns0:ArrProductosIncluidos>
          </xsl:for-each>
        </ns0:ArrServiciosIncluidos>
      </xsl:for-each>
      <xsl:for-each select="/ns0:processResponse/ns0:ArrServiciosAdicionales">
        <ns0:ArrServiciosAdicionales>
          <ns0:Id>
            <xsl:value-of select="ns0:Id"/>
          </ns0:Id>
          <ns0:Nombre>
            <xsl:value-of select="ns0:Nombre"/>
          </ns0:Nombre>
          <ns0:CantidadEquiposAutomaticos>
            <xsl:value-of select="ns0:CantidadEquiposAutomaticos"/>
          </ns0:CantidadEquiposAutomaticos>
          <ns0:Comentario>
            <xsl:value-of select="ns0:Comentario"/>
          </ns0:Comentario>
          <ns0:MaximoAgregar>
            <xsl:value-of select="ns0:MaximoAgregar"/>
          </ns0:MaximoAgregar>
          <ns0:Nombrecomercial>
            <xsl:value-of select="ns0:Nombrecomercial"/>
          </ns0:Nombrecomercial>
          <ns0:NombreEditable>
            <xsl:value-of select="ns0:NombreEditable"/>
          </ns0:NombreEditable>
          <ns0:PlanId>
            <xsl:value-of select="ns0:PlanId"/>
          </ns0:PlanId>
          <ns0:Precio>
            <xsl:value-of select="ns0:Precio"/>
          </ns0:Precio>
          <ns0:SeActiva>
            <xsl:value-of select="ns0:SeActiva"/>
          </ns0:SeActiva>
          <ns0:SeFactura>
            <xsl:value-of select="ns0:SeFactura"/>
          </ns0:SeFactura>
          <ns0:ServicioId>
            <xsl:value-of select="ns0:ServicioId"/>
          </ns0:ServicioId>
          <ns0:SRV_Mode>
            <xsl:value-of select="ns0:SRV_Mode"/>
          </ns0:SRV_Mode>
          <ns0:TipoServicio>
            <xsl:value-of select="ns0:TipoServicio"/>
          </ns0:TipoServicio>
          <ns0:TipoTelefonia>
            <xsl:value-of select="ns0:TipoTelefonia"/>
          </ns0:TipoTelefonia>
          <xsl:for-each select="ns0:ArrProductosIncluidos">
            <ns0:ArrProductosIncluidos>
              <ns0:Id>
                <xsl:value-of select="ns0:Id"/>
              </ns0:Id>
              <ns0:Nombre>
                <xsl:value-of select="ns0:Nombre"/>
              </ns0:Nombre>
              <ns0:AgrupacionAddon>
                <xsl:value-of select="ns0:AgrupacionAddon"/>
              </ns0:AgrupacionAddon>
              <ns0:CantidadDN>
                <xsl:value-of select="ns0:CantidadDN"/>
              </ns0:CantidadDN>
              <ns0:CantidadTroncal>
                <xsl:value-of select="ns0:CantidadTroncal"/>
              </ns0:CantidadTroncal>
              <ns0:Comentario>
                <xsl:value-of select="ns0:Comentario"/>
              </ns0:Comentario>
              <ns0:EsAutomaticoCiudad>
                <xsl:value-of select="ns0:EsAutomaticoCiudad"/>
              </ns0:EsAutomaticoCiudad>
              <ns0:EsCargoUnico>
                <xsl:value-of select="ns0:EsCargoUnico"/>
              </ns0:EsCargoUnico>
              <ns0:Estatus>
                <xsl:value-of select="ns0:Estatus"/>
              </ns0:Estatus>
              <ns0:EsVisible>
                <xsl:value-of select="ns0:EsVisible"/>
              </ns0:EsVisible>
              <ns0:IdBrmArrear>
                <xsl:value-of select="ns0:IdBrmArrear"/>
              </ns0:IdBrmArrear>
              <ns0:IdBrmCU>
                <xsl:value-of select="ns0:IdBrmCU"/>
              </ns0:IdBrmCU>
              <ns0:IdBrmForward>
                <xsl:value-of select="ns0:IdBrmForward"/>
              </ns0:IdBrmForward>
              <ns0:IEPS>
                <xsl:value-of select="ns0:IEPS"/>
              </ns0:IEPS>
              <ns0:IVA>
                <xsl:value-of select="ns0:IVA"/>
              </ns0:IVA>
              <ns0:MaximoAgregar>
                <xsl:value-of select="ns0:MaximoAgregar"/>
              </ns0:MaximoAgregar>
              <ns0:NombreEditable>
                <xsl:value-of select="ns0:NombreEditable"/>
              </ns0:NombreEditable>
              <ns0:PlanDescuentoId>
                <xsl:value-of select="ns0:PlanDescuentoId"/>
              </ns0:PlanDescuentoId>
              <ns0:Plazo>
                <xsl:value-of select="ns0:Plazo"/>
              </ns0:Plazo>
              <ns0:PrecioBase>
                <xsl:value-of select="ns0:PrecioBase"/>
              </ns0:PrecioBase>
              <ns0:PrecioEditable>
                <xsl:value-of select="ns0:PrecioEditable"/>
              </ns0:PrecioEditable>
              <ns0:PrecioProntoPago>
                <xsl:value-of select="ns0:PrecioProntoPago"/>
              </ns0:PrecioProntoPago>
              <ns0:ProductoPadre>
                <xsl:value-of select="ns0:ProductoPadre"/>
              </ns0:ProductoPadre>
              <ns0:TipoProducto>
                <xsl:value-of select="ns0:TipoProducto"/>
              </ns0:TipoProducto>
              <ns0:IdProducto>
                <xsl:value-of select="ns0:IdProducto"/>
              </ns0:IdProducto>
              <ns0:NameProducto>
                <xsl:value-of select="ns0:NameProducto"/>
              </ns0:NameProducto>
              <ns0:ProductoId>
                <xsl:value-of select="ns0:ProductoId"/>
              </ns0:ProductoId>
              <ns0:Ciudad>
                <xsl:value-of select="ns0:Ciudad"/>
              </ns0:Ciudad>
              <ns0:VelocidadSubida>
                <xsl:value-of select="ns0:VelocidadSubida"/>
              </ns0:VelocidadSubida>
              <ns0:VelocidadBajada>
                <xsl:value-of select="ns0:VelocidadBajada"/>
              </ns0:VelocidadBajada>
              <ns0:TieneIPDinamica>
                <xsl:value-of select="ns0:TieneIPDinamica"/>
              </ns0:TieneIPDinamica>
              <ns0:TieneIPFija>
                <xsl:value-of select="ns0:TieneIPFija"/>
              </ns0:TieneIPFija>
              <ns0:TieneSTBAdicional>
                <xsl:value-of select="ns0:TieneSTBAdicional"/>
              </ns0:TieneSTBAdicional>
              <ns0:EsCCTV>
                <xsl:value-of select="ns0:EsCCTV"/>
              </ns0:EsCCTV>
              <ns0:EsWiFi>
                <xsl:value-of select="ns0:EsWiFi"/>
              </ns0:EsWiFi>
              <ns0:Cantidad>
                <xsl:value-of select="ns0:Cantidad"/>
              </ns0:Cantidad>
              <ns0:EstatusProducto>
                <xsl:value-of select="ns0:EstatusProducto"/>
              </ns0:EstatusProducto>
              <ns0:FechaInicio>
                <xsl:value-of select="ns0:FechaInicio"/>
              </ns0:FechaInicio>
              <ns0:FechaFin>
                <xsl:value-of select="ns0:FechaFin"/>
              </ns0:FechaFin>
              <ns0:ComentarioProducto>
                <xsl:value-of select="ns0:ComentarioProducto"/>
              </ns0:ComentarioProducto>
              <ns0:EsProntoPago>
                <xsl:value-of select="ns0:EsProntoPago"/>
              </ns0:EsProntoPago>
            </ns0:ArrProductosIncluidos>
          </xsl:for-each>
        </ns0:ArrServiciosAdicionales>
      </xsl:for-each>
      <xsl:for-each select="/ns0:processResponse/ns0:ArrProductosAdicionales">
        <ns0:ArrProductosAdicionales>
          <ns0:Id>
            <xsl:value-of select="ns0:Id"/>
          </ns0:Id>
          <ns0:Nombre>
            <xsl:value-of select="ns0:Nombre"/>
          </ns0:Nombre>
          <ns0:AgrupacionAddon>
            <xsl:value-of select="ns0:AgrupacionAddon"/>
          </ns0:AgrupacionAddon>
          <ns0:CantidadDN>
            <xsl:value-of select="ns0:CantidadDN"/>
          </ns0:CantidadDN>
          <ns0:CantidadTroncal>
            <xsl:value-of select="ns0:CantidadTroncal"/>
          </ns0:CantidadTroncal>
          <ns0:Comentario>
            <xsl:value-of select="ns0:Comentario"/>
          </ns0:Comentario>
          <ns0:EsAutomaticoCiudad>
            <xsl:value-of select="ns0:EsAutomaticoCiudad"/>
          </ns0:EsAutomaticoCiudad>
          <ns0:EsCargoUnico>
            <xsl:value-of select="ns0:EsCargoUnico"/>
          </ns0:EsCargoUnico>
          <ns0:Estatus>
            <xsl:value-of select="ns0:Estatus"/>
          </ns0:Estatus>
          <ns0:EsVisible>
            <xsl:value-of select="ns0:EsVisible"/>
          </ns0:EsVisible>
          <ns0:IdBrmArrear>
            <xsl:value-of select="ns0:IdBrmArrear"/>
          </ns0:IdBrmArrear>
          <ns0:IdBrmCU>
            <xsl:value-of select="ns0:IdBrmCU"/>
          </ns0:IdBrmCU>
          <ns0:IdBrmForward>
            <xsl:value-of select="ns0:IdBrmForward"/>
          </ns0:IdBrmForward>
          <ns0:IEPS>
            <xsl:value-of select="ns0:IEPS"/>
          </ns0:IEPS>
          <ns0:IVA>
            <xsl:value-of select="ns0:IVA"/>
          </ns0:IVA>
          <ns0:MaximoAgregar>
            <xsl:value-of select="ns0:MaximoAgregar"/>
          </ns0:MaximoAgregar>
          <ns0:NombreEditable>
            <xsl:value-of select="ns0:NombreEditable"/>
          </ns0:NombreEditable>
          <ns0:PlanDescuentoId>
            <xsl:value-of select="ns0:PlanDescuentoId"/>
          </ns0:PlanDescuentoId>
          <ns0:Plazo>
            <xsl:value-of select="ns0:Plazo"/>
          </ns0:Plazo>
          <ns0:PrecioBase>
            <xsl:value-of select="ns0:PrecioBase"/>
          </ns0:PrecioBase>
          <ns0:PrecioEditable>
            <xsl:value-of select="ns0:PrecioEditable"/>
          </ns0:PrecioEditable>
          <ns0:PrecioProntoPago>
            <xsl:value-of select="ns0:PrecioProntoPago"/>
          </ns0:PrecioProntoPago>
          <ns0:ProductoPadre>
            <xsl:value-of select="ns0:ProductoPadre"/>
          </ns0:ProductoPadre>
          <ns0:TipoProducto>
            <xsl:value-of select="ns0:TipoProducto"/>
          </ns0:TipoProducto>
          <ns0:TipoProductoTexto>
            <xsl:value-of select="ns0:TipoProductoTexto"/>
          </ns0:TipoProductoTexto>
          <ns0:IdProducto>
            <xsl:value-of select="ns0:IdProducto"/>
          </ns0:IdProducto>
          <ns0:NameProducto>
            <xsl:value-of select="ns0:NameProducto"/>
          </ns0:NameProducto>
          <ns0:ProductoId>
            <xsl:value-of select="ns0:ProductoId"/>
          </ns0:ProductoId>
          <ns0:Ciudad>
            <xsl:value-of select="ns0:Ciudad"/>
          </ns0:Ciudad>
          <ns0:VelocidadSubida>
            <xsl:value-of select="ns0:VelocidadSubida"/>
          </ns0:VelocidadSubida>
          <ns0:VelocidadBajada>
            <xsl:value-of select="ns0:VelocidadBajada"/>
          </ns0:VelocidadBajada>
          <ns0:TieneIPDinamica>
            <xsl:value-of select="ns0:TieneIPDinamica"/>
          </ns0:TieneIPDinamica>
          <ns0:TieneIPFija>
            <xsl:value-of select="ns0:TieneIPFija"/>
          </ns0:TieneIPFija>
          <ns0:TieneSTBAdicional>
            <xsl:value-of select="ns0:TieneSTBAdicional"/>
          </ns0:TieneSTBAdicional>
          <ns0:EsCCTV>
            <xsl:value-of select="ns0:EsCCTV"/>
          </ns0:EsCCTV>
          <ns0:EsWiFi>
            <xsl:value-of select="ns0:EsWiFi"/>
          </ns0:EsWiFi>
          <ns0:Cantidad>
            <xsl:value-of select="ns0:Cantidad"/>
          </ns0:Cantidad>
          <ns0:EstatusProducto>
            <xsl:value-of select="ns0:EstatusProducto"/>
          </ns0:EstatusProducto>
          <ns0:FechaInicio>
            <xsl:value-of select="ns0:FechaInicio"/>
          </ns0:FechaInicio>
          <ns0:FechaFin>
            <xsl:value-of select="ns0:FechaFin"/>
          </ns0:FechaFin>
          <ns0:ComentarioProducto>
            <xsl:value-of select="ns0:ComentarioProducto"/>
          </ns0:ComentarioProducto>
          <ns0:EsProntoPago>
            <xsl:value-of select="ns0:EsProntoPago"/>
          </ns0:EsProntoPago>
          <xsl:for-each select="ns0:ArrProductosConvivencia">
            <ns0:ArrProductosConvivencia>
              <ns0:Id>
                <xsl:value-of select="ns0:Id"/>
              </ns0:Id>
              <ns0:Name>
                <xsl:value-of select="ns0:Name"/>
              </ns0:Name>
              <ns0:Comentario>
                <xsl:value-of select="ns0:Comentario"/>
              </ns0:Comentario>
              <ns0:Estatus>
                <xsl:value-of select="ns0:Estatus"/>
              </ns0:Estatus>
              <ns0:ProductoId>
                <xsl:value-of select="ns0:ProductoId"/>
              </ns0:ProductoId>
              <ns0:ProductoExcIncId>
                <xsl:value-of select="ns0:ProductoExcIncId"/>
              </ns0:ProductoExcIncId>
              <ns0:Tipo>
                <xsl:value-of select="ns0:Tipo"/>
              </ns0:Tipo>
            </ns0:ArrProductosConvivencia>
          </xsl:for-each>
        </ns0:ArrProductosAdicionales>
      </xsl:for-each>
      <xsl:for-each select="/ns0:processResponse/ns0:ArrPromocionesPlan">
        <ns0:ArrPromocionesPlan>
          <ns0:Id>
            <xsl:value-of select="ns0:Id"/>
          </ns0:Id>
          <ns0:Nombre>
            <xsl:value-of select="ns0:Nombre"/>
          </ns0:Nombre>
          <ns0:Comentario>
            <xsl:value-of select="ns0:Comentario"/>
          </ns0:Comentario>
          <ns0:Descripcion>
            <xsl:value-of select="ns0:Descripcion"/>
          </ns0:Descripcion>
          <ns0:Plan>
            <xsl:value-of select="ns0:Plan"/>
          </ns0:Plan>
          <ns0:PlanCambioParrilla>
            <xsl:value-of select="ns0:PlanCambioParrilla"/>
          </ns0:PlanCambioParrilla>
          <ns0:Promocion>
            <xsl:value-of select="ns0:Promocion"/>
          </ns0:Promocion>
          <ns0:Estatus>
            <xsl:value-of select="ns0:Estatus"/>
          </ns0:Estatus>
          <ns0:Plazo>
            <xsl:value-of select="ns0:Plazo"/>
          </ns0:Plazo>
          <ns0:EstatusPromociones>
            <xsl:value-of select="ns0:EstatusPromociones"/>
          </ns0:EstatusPromociones>
          <ns0:ComentarioPromocion>
            <xsl:value-of select="ns0:ComentarioPromocion"/>
          </ns0:ComentarioPromocion>
          <ns0:NombrePromocion>
            <xsl:value-of select="ns0:NombrePromocion"/>
          </ns0:NombrePromocion>
          <ns0:CompaniaId>
            <xsl:value-of select="ns0:CompaniaId"/>
          </ns0:CompaniaId>
          <ns0:EsAutomatica>
            <xsl:value-of select="ns0:EsAutomatica"/>
          </ns0:EsAutomatica>
          <ns0:EsPostVenta>
            <xsl:value-of select="ns0:EsPostVenta"/>
          </ns0:EsPostVenta>
          <ns0:EstatusPromocion>
            <xsl:value-of select="ns0:EstatusPromocion"/>
          </ns0:EstatusPromocion>
          <ns0:EsVentaNueva>
            <xsl:value-of select="ns0:EsVentaNueva"/>
          </ns0:EsVentaNueva>
          <ns0:FechaFin>
            <xsl:value-of select="ns0:FechaFin"/>
          </ns0:FechaFin>
          <ns0:FechaInicio>
            <xsl:value-of select="ns0:FechaInicio"/>
          </ns0:FechaInicio>
          <ns0:IdPromocion>
            <xsl:value-of select="ns0:IdPromocion"/>
          </ns0:IdPromocion>
          <xsl:for-each select="ns0:ArrPromocionesConvivencia">
            <ns0:ArrPromocionesConvivencia>
              <ns0:Id>
                <xsl:value-of select="ns0:Id"/>
              </ns0:Id>
              <ns0:Nombre>
                <xsl:value-of select="ns0:Nombre"/>
              </ns0:Nombre>
              <ns0:Estatus>
                <xsl:value-of select="ns0:Estatus"/>
              </ns0:Estatus>
              <ns0:PromocionPlanId>
                <xsl:value-of select="ns0:PromocionPlanId"/>
              </ns0:PromocionPlanId>
              <ns0:PromocionExcId>
                <xsl:value-of select="ns0:PromocionExcId"/>
              </ns0:PromocionExcId>
            </ns0:ArrPromocionesConvivencia>
          </xsl:for-each>
          <xsl:for-each select="ns0:ArrPromocionesDetalle">
            <ns0:ArrPromocionesDetalle>
              <ns0:Id>
                <xsl:value-of select="ns0:Id"/>
              </ns0:Id>
              <ns0:Nombre>
                <xsl:value-of select="ns0:Nombre"/>
              </ns0:Nombre>
              <ns0:CAT_CanalVenta>
                <xsl:value-of select="ns0:CAT_CanalVenta"/>
              </ns0:CAT_CanalVenta>
              <ns0:CAT_Ciudad>
                <xsl:value-of select="ns0:CAT_Ciudad"/>
              </ns0:CAT_Ciudad>
              <ns0:CAT_Cluster>
                <xsl:value-of select="ns0:CAT_Cluster"/>
              </ns0:CAT_Cluster>
              <ns0:CAT_Plazo>
                <xsl:value-of select="ns0:CAT_Plazo"/>
              </ns0:CAT_Plazo>
              <ns0:CodigoPostal>
                <xsl:value-of select="ns0:CodigoPostal"/>
              </ns0:CodigoPostal>
              <ns0:CAT_TipoPago>
                <xsl:value-of select="ns0:CAT_TipoPago"/>
              </ns0:CAT_TipoPago>
              <ns0:DP_Promocion>
                <xsl:value-of select="ns0:DP_Promocion"/>
              </ns0:DP_Promocion>
              <ns0:Estatus>
                <xsl:value-of select="ns0:Estatus"/>
              </ns0:Estatus>
            </ns0:ArrPromocionesDetalle>
          </xsl:for-each>
          <xsl:for-each select="ns0:ArrDP_PromocionesServicioProducto">
            <ns0:ArrDP_PromocionesServicioProducto>
              <ns0:Id>
                <xsl:value-of select="ns0:Id"/>
              </ns0:Id>
              <ns0:Nombre>
                <xsl:value-of select="ns0:Nombre"/>
              </ns0:Nombre>
              <ns0:AgregarServicio>
                <xsl:value-of select="ns0:AgregarServicio"/>
              </ns0:AgregarServicio>
              <ns0:EsCargoUnico>
                <xsl:value-of select="ns0:EsCargoUnico"/>
              </ns0:EsCargoUnico>
              <ns0:Estatus>
                <xsl:value-of select="ns0:Estatus"/>
              </ns0:Estatus>
              <ns0:IEPS>
                <xsl:value-of select="ns0:IEPS"/>
              </ns0:IEPS>
              <ns0:IVA>
                <xsl:value-of select="ns0:IVA"/>
              </ns0:IVA>
              <ns0:MesInicio>
                <xsl:value-of select="ns0:MesInicio"/>
              </ns0:MesInicio>
              <ns0:Monto__c>
                <xsl:value-of select="ns0:Monto__c"/>
              </ns0:Monto__c>
              <ns0:PlanServicio>
                <xsl:value-of select="ns0:PlanServicio"/>
              </ns0:PlanServicio>
              <ns0:Porcentaje>
                <xsl:value-of select="ns0:Porcentaje"/>
              </ns0:Porcentaje>
              <ns0:ProductoCaracteristica>
                <xsl:value-of select="ns0:ProductoCaracteristica"/>
              </ns0:ProductoCaracteristica>
              <ns0:PromocionPlan>
                <xsl:value-of select="ns0:PromocionPlan"/>
              </ns0:PromocionPlan>
              <ns0:ServicioProducto>
                <xsl:value-of select="ns0:ServicioProducto"/>
              </ns0:ServicioProducto>
              <ns0:VigenciaMes>
                <xsl:value-of select="ns0:VigenciaMes"/>
              </ns0:VigenciaMes>
              <ns0:IdProductoC>
                <xsl:value-of select="ns0:IdProductoC"/>
              </ns0:IdProductoC>
              <ns0:NameProductoC>
                <xsl:value-of select="ns0:NameProductoC"/>
              </ns0:NameProductoC>
              <ns0:ProductoId>
                <xsl:value-of select="ns0:ProductoId"/>
              </ns0:ProductoId>
              <ns0:Ciudad>
                <xsl:value-of select="ns0:Ciudad"/>
              </ns0:Ciudad>
              <ns0:VelocidadSubida>
                <xsl:value-of select="ns0:VelocidadSubida"/>
              </ns0:VelocidadSubida>
              <ns0:VelocidadBajada>
                <xsl:value-of select="ns0:VelocidadBajada"/>
              </ns0:VelocidadBajada>
              <ns0:TieneIPDinamica>
                <xsl:value-of select="ns0:TieneIPDinamica"/>
              </ns0:TieneIPDinamica>
              <ns0:TieneIPFija>
                <xsl:value-of select="ns0:TieneIPFija"/>
              </ns0:TieneIPFija>
              <ns0:TieneSTBAdicional>
                <xsl:value-of select="ns0:TieneSTBAdicional"/>
              </ns0:TieneSTBAdicional>
              <ns0:EsCCTV>
                <xsl:value-of select="ns0:EsCCTV"/>
              </ns0:EsCCTV>
              <ns0:EsWiFi>
                <xsl:value-of select="ns0:EsWiFi"/>
              </ns0:EsWiFi>
              <ns0:Cantidad>
                <xsl:value-of select="ns0:Cantidad"/>
              </ns0:Cantidad>
              <ns0:EstatusProductoC>
                <xsl:value-of select="ns0:EstatusProductoC"/>
              </ns0:EstatusProductoC>
              <ns0:FechaInicio>
                <xsl:value-of select="ns0:FechaInicio"/>
              </ns0:FechaInicio>
              <ns0:FechaFin>
                <xsl:value-of select="ns0:FechaFin"/>
              </ns0:FechaFin>
              <ns0:Comentario>
                <xsl:value-of select="ns0:Comentario"/>
              </ns0:Comentario>
              <ns0:EsProntoPago>
                <xsl:value-of select="ns0:EsProntoPago"/>
              </ns0:EsProntoPago>
              <ns0:DP_ServicioProducto>
                <ns0:Id>
                  <xsl:value-of select="ns0:DP_ServicioProducto/ns0:Id"/>
                </ns0:Id>
                <ns0:Nombre>
                  <xsl:value-of select="ns0:DP_ServicioProducto/ns0:Nombre"/>
                </ns0:Nombre>
                <ns0:AgrupacionAddon>
                  <xsl:value-of select="ns0:DP_ServicioProducto/ns0:AgrupacionAddon"/>
                </ns0:AgrupacionAddon>
                <ns0:CantidadDN>
                  <xsl:value-of select="ns0:DP_ServicioProducto/ns0:CantidadDN"/>
                </ns0:CantidadDN>
                <ns0:CantidadTroncal>
                  <xsl:value-of select="ns0:DP_ServicioProducto/ns0:CantidadTroncal"/>
                </ns0:CantidadTroncal>
                <ns0:Comentario>
                  <xsl:value-of select="ns0:DP_ServicioProducto/ns0:Comentario"/>
                </ns0:Comentario>
                <ns0:EsAutomaticoCiudad>
                  <xsl:value-of select="ns0:DP_ServicioProducto/ns0:EsAutomaticoCiudad"/>
                </ns0:EsAutomaticoCiudad>
                <ns0:EsCargoUnico>
                  <xsl:value-of select="ns0:DP_ServicioProducto/ns0:EsCargoUnico"/>
                </ns0:EsCargoUnico>
                <ns0:Estatus>
                  <xsl:value-of select="ns0:DP_ServicioProducto/ns0:Estatus"/>
                </ns0:Estatus>
                <ns0:EsVisible>
                  <xsl:value-of select="ns0:DP_ServicioProducto/ns0:EsVisible"/>
                </ns0:EsVisible>
                <ns0:IdBrmArrear>
                  <xsl:value-of select="ns0:DP_ServicioProducto/ns0:IdBrmArrear"/>
                </ns0:IdBrmArrear>
                <ns0:IdBrmCU>
                  <xsl:value-of select="ns0:DP_ServicioProducto/ns0:IdBrmCU"/>
                </ns0:IdBrmCU>
                <ns0:IdBrmForward>
                  <xsl:value-of select="ns0:DP_ServicioProducto/ns0:IdBrmForward"/>
                </ns0:IdBrmForward>
                <ns0:IEPS>
                  <xsl:value-of select="ns0:DP_ServicioProducto/ns0:IEPS"/>
                </ns0:IEPS>
                <ns0:MaximoAgregar>
                  <xsl:value-of select="ns0:DP_ServicioProducto/ns0:MaximoAgregar"/>
                </ns0:MaximoAgregar>
                <ns0:NombreEditable>
                  <xsl:value-of select="ns0:DP_ServicioProducto/ns0:NombreEditable"/>
                </ns0:NombreEditable>
                <ns0:PlanDescuentoId>
                  <xsl:value-of select="ns0:DP_ServicioProducto/ns0:PlanDescuentoId"/>
                </ns0:PlanDescuentoId>
                <ns0:Plazo>
                  <xsl:value-of select="ns0:DP_ServicioProducto/ns0:Plazo"/>
                </ns0:Plazo>
                <ns0:PrecioBase>
                  <xsl:value-of select="ns0:DP_ServicioProducto/ns0:PrecioBase"/>
                </ns0:PrecioBase>
                <ns0:PrecioEditable>
                  <xsl:value-of select="ns0:DP_ServicioProducto/ns0:PrecioEditable"/>
                </ns0:PrecioEditable>
                <ns0:PrecioProntoPago>
                  <xsl:value-of select="ns0:DP_ServicioProducto/ns0:PrecioProntoPago"/>
                </ns0:PrecioProntoPago>
                <ns0:ProductoPadre>
                  <xsl:value-of select="ns0:DP_ServicioProducto/ns0:ProductoPadre"/>
                </ns0:ProductoPadre>
                <ns0:TipoProducto>
                  <xsl:value-of select="ns0:DP_ServicioProducto/ns0:TipoProducto"/>
                </ns0:TipoProducto>
                <ns0:TipoProductoTexto>
                  <xsl:value-of select="ns0:DP_ServicioProducto/ns0:TipoProductoTexto"/>
                </ns0:TipoProductoTexto>
                <ns0:IdProducto>
                  <xsl:value-of select="ns0:DP_ServicioProducto/ns0:IdProducto"/>
                </ns0:IdProducto>
                <ns0:NameProducto>
                  <xsl:value-of select="ns0:DP_ServicioProducto/ns0:NameProducto"/>
                </ns0:NameProducto>
                <ns0:ProductoId>
                  <xsl:value-of select="ns0:DP_ServicioProducto/ns0:ProductoId"/>
                </ns0:ProductoId>
                <ns0:Ciudad>
                  <xsl:value-of select="ns0:DP_ServicioProducto/ns0:Ciudad"/>
                </ns0:Ciudad>
                <ns0:VelocidadSubida>
                  <xsl:value-of select="ns0:DP_ServicioProducto/ns0:VelocidadSubida"/>
                </ns0:VelocidadSubida>
                <ns0:VelocidadBajada>
                  <xsl:value-of select="ns0:DP_ServicioProducto/ns0:VelocidadBajada"/>
                </ns0:VelocidadBajada>
                <ns0:TieneIPDinamica>
                  <xsl:value-of select="ns0:DP_ServicioProducto/ns0:TieneIPDinamica"/>
                </ns0:TieneIPDinamica>
                <ns0:TieneIPFija>
                  <xsl:value-of select="ns0:DP_ServicioProducto/ns0:TieneIPFija"/>
                </ns0:TieneIPFija>
                <ns0:TieneSTBAdicional>
                  <xsl:value-of select="ns0:DP_ServicioProducto/ns0:TieneSTBAdicional"/>
                </ns0:TieneSTBAdicional>
                <ns0:EsCCTV>
                  <xsl:value-of select="ns0:DP_ServicioProducto/ns0:EsCCTV"/>
                </ns0:EsCCTV>
                <ns0:EsWiFi>
                  <xsl:value-of select="ns0:DP_ServicioProducto/ns0:EsWiFi"/>
                </ns0:EsWiFi>
                <ns0:Cantidad>
                  <xsl:value-of select="ns0:DP_ServicioProducto/ns0:Cantidad"/>
                </ns0:Cantidad>
                <ns0:EstatusProducto>
                  <xsl:value-of select="ns0:DP_ServicioProducto/ns0:EstatusProducto"/>
                </ns0:EstatusProducto>
                <ns0:FechaInicio>
                  <xsl:value-of select="ns0:DP_ServicioProducto/ns0:FechaInicio"/>
                </ns0:FechaInicio>
                <ns0:FechaFin>
                  <xsl:value-of select="ns0:DP_ServicioProducto/ns0:FechaFin"/>
                </ns0:FechaFin>
                <ns0:ComentarioProducto>
                  <xsl:value-of select="ns0:DP_ServicioProducto/ns0:ComentarioProducto"/>
                </ns0:ComentarioProducto>
                <ns0:EsProntoPago>
                  <xsl:value-of select="ns0:DP_ServicioProducto/ns0:EsProntoPago"/>
                </ns0:EsProntoPago>
                <ns0:IdPromocionSP>
                  <xsl:value-of select="ns0:DP_ServicioProducto/ns0:IdPromocionSP"/>
                </ns0:IdPromocionSP>
                <xsl:for-each select="ns0:DP_ServicioProducto/ns0:ArrProductosConvivencia">
                  <ns0:ArrProductosConvivencia>
                    <ns0:Id>
                      <xsl:value-of select="ns0:Id"/>
                    </ns0:Id>
                    <ns0:Name>
                      <xsl:value-of select="ns0:Name"/>
                    </ns0:Name>
                    <ns0:Comentario>
                      <xsl:value-of select="ns0:Comentario"/>
                    </ns0:Comentario>
                    <ns0:Estatus>
                      <xsl:value-of select="ns0:Estatus"/>
                    </ns0:Estatus>
                    <ns0:ProductoId>
                      <xsl:value-of select="ns0:ProductoId"/>
                    </ns0:ProductoId>
                    <ns0:ProductoExcIncId>
                      <xsl:value-of select="ns0:ProductoExcIncId"/>
                    </ns0:ProductoExcIncId>
                    <ns0:Tipo>
                      <xsl:value-of select="ns0:Tipo"/>
                    </ns0:Tipo>
                  </ns0:ArrProductosConvivencia>
                </xsl:for-each>
              </ns0:DP_ServicioProducto>
            </ns0:ArrDP_PromocionesServicioProducto>
          </xsl:for-each>
        </ns0:ArrPromocionesPlan>
      </xsl:for-each>
    </ns0:processResponse>
  </xsl:template>
</xsl:stylesheet>
