<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="PM_ServicesProducts" targetNamespace="http://xmlns.oracle.com/VentasMovil/PM_ServicesProducts/PM_ServicesProducts" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://xmlns.oracle.com/VentasMovil/PM_ServicesProducts/PM_ServicesProducts" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://xmlns.oracle.com/VentasMovil/PM_ServicesProducts/PM_ServicesProducts" schemaLocation="../Schemas/PM_ServicesProducts.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="PM_ServicesProductsRequestMessage">
      <wsdl:part name="payload" element="client:process"/>
   </wsdl:message>
   <wsdl:message name="PM_ServicesProductsResponseMessage">
      <wsdl:part name="payload" element="client:processResponse"/>
   </wsdl:message>
   <wsdl:portType name="PM_ServicesProducts">
      <wsdl:operation name="process">
         <wsdl:input message="client:PM_ServicesProductsRequestMessage"/>
         <wsdl:output message="client:PM_ServicesProductsResponseMessage"/>
      </wsdl:operation>
   </wsdl:portType>
   <plnk:partnerLinkType name="PM_ServicesProducts">
      <plnk:role name="PM_ServicesProductsProvider" portType="client:PM_ServicesProducts"/>
   </plnk:partnerLinkType>
</wsdl:definitions>
